revoke delete on table "public"."uma_lookup" from "anon";

revoke insert on table "public"."uma_lookup" from "anon";

revoke references on table "public"."uma_lookup" from "anon";

revoke select on table "public"."uma_lookup" from "anon";

revoke trigger on table "public"."uma_lookup" from "anon";

revoke truncate on table "public"."uma_lookup" from "anon";

revoke update on table "public"."uma_lookup" from "anon";

revoke delete on table "public"."uma_lookup" from "authenticated";

revoke insert on table "public"."uma_lookup" from "authenticated";

revoke references on table "public"."uma_lookup" from "authenticated";

revoke select on table "public"."uma_lookup" from "authenticated";

revoke trigger on table "public"."uma_lookup" from "authenticated";

revoke truncate on table "public"."uma_lookup" from "authenticated";

revoke update on table "public"."uma_lookup" from "authenticated";

revoke delete on table "public"."uma_lookup" from "service_role";

revoke insert on table "public"."uma_lookup" from "service_role";

revoke references on table "public"."uma_lookup" from "service_role";

revoke select on table "public"."uma_lookup" from "service_role";

revoke trigger on table "public"."uma_lookup" from "service_role";

revoke truncate on table "public"."uma_lookup" from "service_role";

revoke update on table "public"."uma_lookup" from "service_role";

alter table "public"."uma_lookup" drop constraint "uma_table_pkey";

drop index if exists "public"."uma_table_pkey";

drop table "public"."uma_lookup";


  create table "public"."uma_positional_lookup" (
    "uma_id" smallint generated by default as identity not null,
    "uma_rank1" integer not null,
    "uma_rank2" integer not null,
    "uma_rank3" integer not null,
    "uma_rank4" integer not null,
    "purpose" text not null,
    "category" text not null,
    "status" boolean not null default true,
    "total_uma" integer generated always as ((((uma_rank1 + uma_rank2) + uma_rank3) + uma_rank4)) stored,
    "gap_1_2" integer generated always as ((uma_rank1 - uma_rank2)) stored,
    "gap_2_3" integer generated always as ((uma_rank2 - uma_rank3)) stored,
    "gap_3_4" integer generated always as ((uma_rank3 - uma_rank4)) stored,
    "play_style" text generated always as (
CASE
    WHEN (((uma_rank1 - uma_rank2) = (uma_rank2 - uma_rank3)) AND ((uma_rank2 - uma_rank3) = (uma_rank3 - uma_rank4))) THEN 'Equal Positional Emphasis'::text
    WHEN (((uma_rank1 - uma_rank2) = (uma_rank3 - uma_rank4)) AND ((uma_rank1 - uma_rank2) > (uma_rank2 - uma_rank3))) THEN 'Barbell Emphasis'::text
    WHEN (((uma_rank2 - uma_rank3) > (uma_rank1 - uma_rank2)) AND ((uma_rank2 - uma_rank3) > (uma_rank3 - uma_rank4))) THEN 'Middle Split Emphasis'::text
    WHEN (((uma_rank1 - uma_rank2) > (uma_rank2 - uma_rank3)) AND ((uma_rank1 - uma_rank2) > (uma_rank3 - uma_rank4))) THEN 'First Place Emphasis'::text
    WHEN (((uma_rank3 - uma_rank4) > (uma_rank1 - uma_rank2)) AND ((uma_rank3 - uma_rank4) > (uma_rank2 - uma_rank3))) THEN 'Last Place Avoidance'::text
    ELSE 'Asymmetric/Mixed'::text
END) stored,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."uma_positional_lookup" enable row level security;

CREATE UNIQUE INDEX uma_table_pkey ON public.uma_positional_lookup USING btree (uma_id);

alter table "public"."uma_positional_lookup" add constraint "uma_table_pkey" PRIMARY KEY using index "uma_table_pkey";

grant delete on table "public"."uma_positional_lookup" to "anon";

grant insert on table "public"."uma_positional_lookup" to "anon";

grant references on table "public"."uma_positional_lookup" to "anon";

grant select on table "public"."uma_positional_lookup" to "anon";

grant trigger on table "public"."uma_positional_lookup" to "anon";

grant truncate on table "public"."uma_positional_lookup" to "anon";

grant update on table "public"."uma_positional_lookup" to "anon";

grant delete on table "public"."uma_positional_lookup" to "authenticated";

grant insert on table "public"."uma_positional_lookup" to "authenticated";

grant references on table "public"."uma_positional_lookup" to "authenticated";

grant select on table "public"."uma_positional_lookup" to "authenticated";

grant trigger on table "public"."uma_positional_lookup" to "authenticated";

grant truncate on table "public"."uma_positional_lookup" to "authenticated";

grant update on table "public"."uma_positional_lookup" to "authenticated";

grant delete on table "public"."uma_positional_lookup" to "service_role";

grant insert on table "public"."uma_positional_lookup" to "service_role";

grant references on table "public"."uma_positional_lookup" to "service_role";

grant select on table "public"."uma_positional_lookup" to "service_role";

grant trigger on table "public"."uma_positional_lookup" to "service_role";

grant truncate on table "public"."uma_positional_lookup" to "service_role";

grant update on table "public"."uma_positional_lookup" to "service_role";


