-- Recreate yaku_lookup (accidentally dropped in prior migration)
CREATE TABLE yaku_lookup (
    yaku_id             int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yaku_name           text NOT NULL UNIQUE,
    han_value           int4 NOT NULL,
    open_hand_penalty   bool NOT NULL DEFAULT false,
    is_yakuman          bool NOT NULL DEFAULT false,
    is_double_yakuman   bool NOT NULL DEFAULT false,
    closed_only         bool NOT NULL DEFAULT false
);

COMMENT ON TABLE yaku_lookup IS 'Static reference table of yaku names and han values. Nagashi Mangan and Renhou excluded on purpose — their value is ruleset-defined, not fixed, and is handled via rule_details at scoring time instead.';
COMMENT ON COLUMN yaku_lookup.han_value IS 'Base han for closed hand (or fixed value for yaku with no open/closed distinction). If open_hand_penalty = true and hand is open, effective han = han_value - 1.';
COMMENT ON COLUMN yaku_lookup.open_hand_penalty IS 'If true, this yaku loses 1 han when the hand is open. Only relevant if closed_only = false.';
COMMENT ON COLUMN yaku_lookup.closed_only IS 'If true, this yaku cannot be awarded on an open hand at all — validate at application layer, do not encode as a 0-han row.';
COMMENT ON COLUMN yaku_lookup.is_double_yakuman IS 'If true, whether this counts as double yakuman (26 han) depends on the ruleset double_yakuman flag — check rule_details before applying.';

-- Wipe test data on hand_info and hand_result — shape is changing under them, confirmed OK with data owner.
TRUNCATE TABLE hand_result;
TRUNCATE TABLE hand_info RESTART IDENTITY CASCADE;

-- hand_win: one row per winning claim. Double/triple ron = multiple rows, same hand_id, different winner_pid.
CREATE TABLE hand_win (
    ihid        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hand_id     bigint NOT NULL REFERENCES hand_info(hand_id),
    winner_pid  int4 NOT NULL REFERENCES player_info(player_id),
    is_tsumo    bool NOT NULL,
    han         int4 NOT NULL,
    fu          int4 NOT NULL,
    value       int4 NOT NULL,
    created_at  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (hand_id, winner_pid)
);

COMMENT ON TABLE hand_win IS 'One row per winning claim. Double/triple ron = multiple rows, same hand_id, different winner_pid. Replaces yakuman_record and the han/fu/hand_value columns formerly on hand_info. game_id intentionally not stored — derive via hand_id -> hand_info -> game_id.';

-- hand_yaku: junction, one hand_win claim can have multiple yaku (double yakuman, stacked yaku, etc.)
CREATE TABLE hand_yaku (
    ihid     bigint NOT NULL REFERENCES hand_win(ihid),
    yaku_id  int4 NOT NULL REFERENCES yaku_lookup(yaku_id),
    PRIMARY KEY (ihid, yaku_id)
);

COMMENT ON TABLE hand_yaku IS 'Junction table: which yaku were part of a given winning claim (hand_win.ihid). Supports multi-yaku hands including stacked/double yakuman.';

-- Drop yakuman_record — its purpose is now covered by hand_win + hand_yaku (filter yaku_lookup.is_yakuman = true), was empty.
DROP TABLE yakuman_record;

-- Strip winner-specific facts off hand_info — they never belonged there and caused the is_multiple_ron/main_hid dead-end.
ALTER TABLE hand_info
  DROP COLUMN han,
  DROP COLUMN fu,
  DROP COLUMN hand_value,
  DROP COLUMN is_multiple_ron,
  DROP COLUMN main_hid;

COMMENT ON TABLE hand_info IS 'One row per hand played, hand-level facts only (round, wind, honba, riichi deposits, outcome, completion). Winner-specific data (han/fu/value/yaku) lives in hand_win + hand_yaku, not here.';
