alter table "public"."uma_positional_lookup" drop constraint "uma_table_pkey";

drop index if exists "public"."uma_table_pkey";

alter table "public"."game_info" drop column "uma_id";

alter table "public"."game_info" add column "positional_uma_id" smallint;

alter table "public"."ruleset_info" drop column "uma_id";

alter table "public"."ruleset_info" add column "positional_uma_id" smallint;

alter table "public"."uma_positional_lookup" drop column "uma_id";

alter table "public"."uma_positional_lookup" add column "positional_uma_id" smallint generated by default as identity not null;

CREATE UNIQUE INDEX uma_table_pkey ON public.uma_positional_lookup USING btree (positional_uma_id);

alter table "public"."uma_positional_lookup" add constraint "uma_table_pkey" PRIMARY KEY using index "uma_table_pkey";


