-- ============================================================
-- Migration: event_model_consolidation
-- Applied remotely 2026-09-12 via MCP. This file exists so the
-- local migration history matches remote.
--
-- Merges local tournaments + overseas events into event_info,
-- links games to events, protects manual records from replay.
-- Does NOT drop `mode` — that is a later migration.
-- ============================================================

-- 1. Enums --------------------------------------------------

create type event_type_enum as enum (
    'private',
    'club',
    'league',
    'tournament'
);

create type result_source_enum as enum (
    'derived',
    'manual'
);

-- 2. Format lookup table ------------------------------------

create table event_format (
    format_id   smallint primary key generated by default as identity,
    name        text not null unique,
    description text,
    status      boolean not null default true
);

comment on table event_format is
    'Competition structure lookup. Open set — new formats are inserted via the admin panel, not migrated.';

insert into event_format (name) values
    ('Rd-Robin'),
    ('Rd-Robin with Split Brackets'),
    ('Danish System');

-- 3. event_info ---------------------------------------------

alter table event_info
    add column event_type      event_type_enum not null default 'tournament',
    add column format_id       smallint references event_format(format_id),
    add column parent_event_id integer references event_info(event_id),
    add column venue_id        integer references venue(venue_id);

comment on column event_info.event_type is
    'Category of event. Replaces the legacy mode table once game_info.mode_id is retired.';

comment on column event_info.format_id is
    'Competition structure. Null for overseas events — not reported by external organisers.';

comment on column event_info.parent_event_id is
    'Self-reference for hierarchy: season -> league, bracket -> tournament. Null = top level.';

comment on column event_info.venue_id is
    'DECLARED venue, set at event creation before games exist. NON-AUTHORITATIVE. For actual venue of play, always use game_info.venue_id. Null for leagues, standing events, and overseas events.';

alter table event_info
    add constraint event_info_parent_not_self
    check (parent_event_id is distinct from event_id);

alter table event_info
    add constraint event_info_one_locator
    check (venue_id is null or location is null);

create index idx_event_info_parent on event_info(parent_event_id);
create index idx_event_info_type   on event_info(event_type);

-- 4. game_info ----------------------------------------------

alter table game_info
    add column event_id integer references event_info(event_id);

comment on column game_info.event_id is
    'The event this game belongs to. Nullable during backfill; tighten to NOT NULL once historical rows are mapped. game_info.venue_id remains authoritative for location.';

create index idx_game_info_event on game_info(event_id);

-- 5. event_result -------------------------------------------

alter table event_result
    alter column event_id type integer;

alter table event_result
    add column source result_source_enum not null default 'derived';

comment on column event_result.source is
    'Provenance guard. The Python pipeline MUST scope all deletes/upserts to source = ''derived''. Rows marked manual have no underlying games and would be destroyed by a full replay.';

create index idx_event_result_source on event_result(source);
