revoke delete on table "public"."game_ruleset" from "anon";

revoke insert on table "public"."game_ruleset" from "anon";

revoke references on table "public"."game_ruleset" from "anon";

revoke select on table "public"."game_ruleset" from "anon";

revoke trigger on table "public"."game_ruleset" from "anon";

revoke truncate on table "public"."game_ruleset" from "anon";

revoke update on table "public"."game_ruleset" from "anon";

revoke delete on table "public"."game_ruleset" from "authenticated";

revoke insert on table "public"."game_ruleset" from "authenticated";

revoke references on table "public"."game_ruleset" from "authenticated";

revoke select on table "public"."game_ruleset" from "authenticated";

revoke trigger on table "public"."game_ruleset" from "authenticated";

revoke truncate on table "public"."game_ruleset" from "authenticated";

revoke update on table "public"."game_ruleset" from "authenticated";

revoke delete on table "public"."game_ruleset" from "service_role";

revoke insert on table "public"."game_ruleset" from "service_role";

revoke references on table "public"."game_ruleset" from "service_role";

revoke select on table "public"."game_ruleset" from "service_role";

revoke trigger on table "public"."game_ruleset" from "service_role";

revoke truncate on table "public"."game_ruleset" from "service_role";

revoke update on table "public"."game_ruleset" from "service_role";

alter table "public"."game_ruleset" drop constraint "game_ruleset_reference_ruleset_id_fkey";

alter table "public"."uma_lookup" drop constraint "uma_lookup_description_unique";

alter table "public"."event_info" drop constraint "event_ruleset_id_fkey";

alter table "public"."game_info" drop constraint "game_info_ruleset_id_fkey";

alter table "public"."game_ruleset" drop constraint "game_ruleset_pkey";

alter table "public"."uma_lookup" drop constraint "uma_lookup_pkey";

alter table "public"."ruleset_info" drop constraint "ruleset_pkey";

drop index if exists "public"."game_ruleset_pkey";

drop index if exists "public"."idx_uma_lookup_category";

drop index if exists "public"."idx_uma_lookup_status";

drop index if exists "public"."uma_lookup_description_unique";

drop index if exists "public"."uma_lookup_pkey";

drop index if exists "public"."ruleset_pkey";

drop table "public"."game_ruleset";

alter table "public"."game_info" add column "uma_id" smallint;

alter table "public"."game_info" alter column "ruleset_id" set data type smallint using "ruleset_id"::smallint;

alter table "public"."ruleset_info" drop column "id";

alter table "public"."ruleset_info" add column "ruleset_id" smallint generated by default as identity not null;

alter table "public"."ruleset_info" add column "uma_id" smallint;

alter table "public"."uma_lookup" drop column "description";

alter table "public"."uma_lookup" alter column "purpose" set not null;

alter table "public"."uma_lookup" alter column "uma_id" set generated by default;

alter table "public"."uma_lookup" enable row level security;

CREATE UNIQUE INDEX uma_table_pkey ON public.uma_lookup USING btree (uma_id);

CREATE UNIQUE INDEX ruleset_pkey ON public.ruleset_info USING btree (ruleset_id);

alter table "public"."uma_lookup" add constraint "uma_table_pkey" PRIMARY KEY using index "uma_table_pkey";

alter table "public"."ruleset_info" add constraint "ruleset_pkey" PRIMARY KEY using index "ruleset_pkey";

alter table "public"."event_info" add constraint "event_ruleset_id_fkey" FOREIGN KEY (ruleset_id) REFERENCES public.ruleset_info(ruleset_id) not valid;

alter table "public"."event_info" validate constraint "event_ruleset_id_fkey";

alter table "public"."game_info" add constraint "game_info_ruleset_id_fkey" FOREIGN KEY (ruleset_id) REFERENCES public.ruleset_info(ruleset_id) not valid;

alter table "public"."game_info" validate constraint "game_info_ruleset_id_fkey";


