revoke delete on table "public"."user_roles" from "anon";

revoke insert on table "public"."user_roles" from "anon";

revoke select on table "public"."user_roles" from "anon";

revoke update on table "public"."user_roles" from "anon";

revoke delete on table "public"."user_roles" from "authenticated";

revoke insert on table "public"."user_roles" from "authenticated";

revoke select on table "public"."user_roles" from "authenticated";

revoke update on table "public"."user_roles" from "authenticated";

revoke delete on table "public"."user_roles" from "service_role";

revoke insert on table "public"."user_roles" from "service_role";

revoke select on table "public"."user_roles" from "service_role";

revoke update on table "public"."user_roles" from "service_role";

alter table "public"."player_details" drop constraint "player_details_pid_fkey";

alter table "public"."game_info" drop constraint "game_info_venue_id_fkey";

alter table "public"."mode" drop constraint "mode_venue_id_fkey";

alter table "public"."player_details" drop constraint "player_details_pkey";

alter table "public"."venue" drop constraint "venue_pkey";

drop index if exists "public"."player_details_pkey";

drop index if exists "public"."venue_pkey";

alter table "public"."event_info" alter column "event_id" set generated by default;

alter table "public"."event_info" alter column "event_id" set data type integer using "event_id"::integer;

alter table "public"."event_info" alter column "ruleset_id" set data type smallint using "ruleset_id"::smallint;

alter table "public"."game_info" drop column "create_at";

alter table "public"."game_info" drop column "submission_stage";

alter table "public"."game_info" add column "created_at" timestamp without time zone default CURRENT_TIMESTAMP;

alter table "public"."game_info" alter column "recorded_by_pid" set data type integer using "recorded_by_pid"::integer;

alter table "public"."player_details" drop column "pid";

alter table "public"."player_details" add column "player_id" integer not null;

alter table "public"."venue" drop column "Venue_id";

alter table "public"."venue" add column "venue_id" integer not null;

CREATE UNIQUE INDEX player_details_pkey ON public.player_details USING btree (player_id);

CREATE UNIQUE INDEX venue_pkey ON public.venue USING btree (venue_id);

alter table "public"."player_details" add constraint "player_details_pkey" PRIMARY KEY using index "player_details_pkey";

alter table "public"."venue" add constraint "venue_pkey" PRIMARY KEY using index "venue_pkey";

alter table "public"."player_details" add constraint "player_details_player_id_fkey" FOREIGN KEY (player_id) REFERENCES public.player_info(player_id) ON DELETE CASCADE not valid;

alter table "public"."player_details" validate constraint "player_details_player_id_fkey";

alter table "public"."game_info" add constraint "game_info_venue_id_fkey" FOREIGN KEY (venue_id) REFERENCES public.venue(venue_id) not valid;

alter table "public"."game_info" validate constraint "game_info_venue_id_fkey";

alter table "public"."mode" add constraint "mode_venue_id_fkey" FOREIGN KEY (venue_id) REFERENCES public.venue(venue_id) not valid;

alter table "public"."mode" validate constraint "mode_venue_id_fkey";


